[params]
description = "A business/corporate style responsive site template."
images = ['images/metaimage.jpg']
show_post_dates = false

[params.footer]

[[params.footer.links]]
header = "Liens vers des trucs"
[[params.footer.links.links]]
title = "Mattis et quis rutrum"
url = "#"

[[params.footer.links]]
header = "More Links to Stuff"
[[params.footer.links.links]]
title = "Duis neque nisi dapibus"
url = "#"

[params.footer.contact_form]
enabled = true
header = "Get In Touch"
action = ""
